# Generated by Django 5.2.8 on 2025-11-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0001_initial'),
        ('products', '0003_product_final_price_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума позиції')),
                ('client_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_product_orders', to='client_orders.clientorder', verbose_name='Замовлення клієнта')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлень',
            },
        ),
    ]
