# Generated by Django 5.2.8 on 2025-11-11 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0002_productorder'),
        ('products', '0003_product_final_price_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Фінальна ціна')),
                ('client_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_orders.clientorder', verbose_name='Замовлення клієнта')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Виріб')),
            ],
            options={
                'verbose_name': 'Елемент замовлення',
                'verbose_name_plural': 'Елементи замовлення',
            },
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
