# Generated by Django 5.2.8 on 2025-11-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0003_clientorderitem_delete_productorder'),
        ('products', '0003_product_final_price_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorderitem',
            name='client_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_orders.clientorder', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='clientorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Виріб'),
        ),
        migrations.AlterField(
            model_name='clientorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість'),
        ),
    ]
