# Generated by Django 5.2.8 on 2025-11-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0004_alter_clientorderitem_client_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorder',
            name='total_price',
        ),
    ]
