# Generated by Django 5.2.8 on 2025-11-11 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0005_remove_clientorder_total_price'),
        ('products', '0003_product_final_price_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientorder',
            options={'ordering': ['-id'], 'verbose_name': 'Замовлення клієнта', 'verbose_name_plural': 'Замовлення клієнтів'},
        ),
        migrations.AlterModelOptions(
            name='clientorderitem',
            options={'verbose_name': 'Елемент замовлення клієнта', 'verbose_name_plural': 'Елементи замовлень клієнтів'},
        ),
        migrations.RemoveField(
            model_name='clientorder',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='clientorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clientorder',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='clientorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='clientorder',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='clientorderitem',
            unique_together={('client_order', 'product')},
        ),
        migrations.AddField(
            model_name='clientorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Загальна ціна'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='clientorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Продукт'),
        ),
        migrations.RemoveField(
            model_name='clientorderitem',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='clientorderitem',
            name='quantity',
        ),
    ]
