# Generated by Django 5.2.8 on 2025-11-07 20:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Адміністратор'), ('OWNER', 'Власник'), ('DESIGNER', 'Дизайнер'), ('SALES_HEAD', 'Керівник з продажів'), ('RETAIL_HEAD', 'Керівник роздрібного продажу'), ('RETAIL_MANAGER', 'Менеджер з продажу'), ('DEALER_HEAD', 'Керівник дилерів'), ('DEALER_MANAGER', 'Партнер / дилер'), ('PRODUCT_HEAD', 'Керівник виробництва'), ('PRODUCT_MANAGER', 'Менеджер виробництва'), ('LOGIST_MANAGER', 'Менеджер з логістики'), ('QUALITY_MANAGER', 'Менеджер ОТК')], db_index=True, default='RETAIL_MANAGER', max_length=32, verbose_name='Роль')),
                ('phone_number', models.CharField(help_text='Контактний номер телефону', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Введіть номер телефону у форматі +380501234567', regex='^\\+?380?\\d{9,12}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Електронна пошта')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Назва компанії')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль дилера',
                'verbose_name_plural': 'Профілі дилерів',
            },
        ),
        migrations.CreateModel(
            name='SalesManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=150, verbose_name='Назва салону')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль менеджера з продажів',
                'verbose_name_plural': 'Профілі менеджерів з продажів',
            },
        ),
    ]
