# Generated by Django 5.2.8 on 2025-11-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_orders', '0001_initial'),
        ('fabric', '0001_initial'),
        ('products', '0003_product_final_price_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сума')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'В роботі'), ('ready', 'Готово'), ('shipped', 'Відправлено'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('client_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='client_orders.clientorder', verbose_name='Замовлення клієнта')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabric.fabric', verbose_name='Тканина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='products.product', verbose_name='Виріб')),
            ],
            options={
                'verbose_name': 'Виробниче замовлення',
                'verbose_name_plural': 'Виробничі замовлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
