# Generated by Django 5.2.8 on 2025-11-11 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_orders', '0001_initial'),
        ('products', '0003_product_final_price_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Замовлення виробу', 'verbose_name_plural': 'Замовлення виробів'},
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='productorder',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Фінальна ціна'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to='products.product', verbose_name='Виріб'),
        ),
    ]
