# Generated by Django 5.2.8 on 2025-11-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_orders', '0006_alter_clientorder_options_and_more'),
        ('product_orders', '0002_alter_productorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='client_order',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productorder',
            name='client_order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='client_orders.clientorderitem', verbose_name='Елемент замовлення клієнта'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фінальна ціна'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['client_order_item'], name='product_ord_client__835712_idx'),
        ),
    ]
