# Generated by Django 5.2.8 on 2025-11-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва виробу')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Довжина (см)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Висота (см)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базова ціна (грн)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис виробу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний в каталозі')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Виріб',
                'verbose_name_plural': 'Вироби',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Фото виробу')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Виріб')),
            ],
            options={
                'verbose_name': 'Фото виробу',
                'verbose_name_plural': 'Фото виробів',
            },
        ),
    ]
