# Generated by Django 5.2.8 on 2025-11-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FabricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис категорії')),
            ],
            options={
                'verbose_name': 'Категорія тканини',
                'verbose_name_plural': 'Категорії тканин',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва тканини')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код тканини')),
                ('color_name', models.CharField(max_length=100, verbose_name='Назва кольору')),
                ('color_code', models.CharField(max_length=20, verbose_name='Код кольору (наприклад HEX або RGB)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fabric_images/', verbose_name='Фото зразка')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Коефіцієнт ціни (множник для базової ціни виробу)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна для вибору')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrics', to='fabric.fabriccategory')),
            ],
            options={
                'verbose_name': 'Тканина',
                'verbose_name_plural': 'Тканини',
            },
        ),
    ]
